/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inventariodetienda;

import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.JFrame;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author alan-
 */
public class FrmMenuPrincipal extends javax.swing.JFrame { 
    
    /**
     * Creates new form MenuPrincipal
     */
    public FrmMenuPrincipal() {
        
        initComponents();
        if (frmLogin.mEsVendedor){
         
            pnlFondo.setBackground(new java.awt.Color(187,41,10));
            this.menuInicio.setVisible(true);
            this.btnVentas.setVisible(true);
            this.menuUsuarios.setVisible(false);
            this.btnBusqueda.setVisible(true);
        }else if (frmLogin.mEsAdmin){
          
            pnlFondo.setBackground(new java.awt.Color(22,144,163));
            this.menuInicio.setVisible(true);
            this.btnVentas.setVisible(true);
            this.menuUsuarios.setVisible(true);
            this.btnBusqueda.setVisible(true);
        }else if (frmLogin.mEsAcomodador){
            
            pnlFondo.setBackground(new java.awt.Color(225,143,0));
            this.menuInicio.setVisible(true);
            this.btnVentas.setVisible(false);
            this.menuUsuarios.setVisible(false);
            this.btnBusqueda.setVisible(true);
        }
        this.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        pnlFondo = new javax.swing.JPanel();
        pnlBlanco = new javax.swing.JPanel();
        lblBienvenido = new javax.swing.JLabel();
        btnVentas = new javax.swing.JButton();
        btnBusqueda = new javax.swing.JButton();
        lblBienvenido1 = new javax.swing.JLabel();
        barraMenu = new javax.swing.JMenuBar();
        menuInicio = new javax.swing.JMenu();
        btnSalir = new javax.swing.JMenuItem();
        menuUsuarios = new javax.swing.JMenu();
        btnCrearUsuario = new javax.swing.JMenuItem();
        btnModificarUsuario = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        btnVerUsuario = new javax.swing.JMenuItem();

        jMenuItem4.setText("jMenuItem4");

        jMenuItem5.setText("jMenuItem5");

        jMenuItem6.setText("jMenuItem6");

        jMenuItem7.setText("jMenuItem7");

        jMenuItem8.setText("jMenuItem8");

        jMenuItem9.setText("jMenuItem9");

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        jMenu5.setText("File");
        jMenuBar3.add(jMenu5);

        jMenu6.setText("Edit");
        jMenuBar3.add(jMenu6);

        jMenu7.setText("jMenu7");

        jMenuItem1.setText("jMenuItem1");

        pnlFondo.setBackground(new java.awt.Color(204, 153, 0));

        javax.swing.GroupLayout pnlFondoLayout = new javax.swing.GroupLayout(pnlFondo);
        pnlFondo.setLayout(pnlFondoLayout);
        pnlFondoLayout.setHorizontalGroup(
            pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 266, Short.MAX_VALUE)
        );
        pnlFondoLayout.setVerticalGroup(
            pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 212, Short.MAX_VALUE)
        );

        pnlBlanco.setBackground(new java.awt.Color(0, 204, 153));

        javax.swing.GroupLayout pnlBlancoLayout = new javax.swing.GroupLayout(pnlBlanco);
        pnlBlanco.setLayout(pnlBlancoLayout);
        pnlBlancoLayout.setHorizontalGroup(
            pnlBlancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 274, Short.MAX_VALUE)
        );
        pnlBlancoLayout.setVerticalGroup(
            pnlBlancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 103, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Inventario de tienda");
        setBackground(new java.awt.Color(102, 204, 0));
        setResizable(false);
        setSize(new java.awt.Dimension(100, 100));

        lblBienvenido.setFont(new java.awt.Font("PMingLiU-ExtB", 1, 24)); // NOI18N
        lblBienvenido.setText("Bienvenido usuario");

        btnVentas.setText("Ventas");
        btnVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVentasActionPerformed(evt);
            }
        });

        btnBusqueda.setText("Busqueda");
        btnBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBusquedaActionPerformed(evt);
            }
        });

        lblBienvenido1.setFont(new java.awt.Font("PMingLiU-ExtB", 1, 24)); // NOI18N

        barraMenu.setFont(new java.awt.Font("Perpetua", 0, 36)); // NOI18N
        barraMenu.setInheritsPopupMenu(true);

        menuInicio.setText("Inicio");

        btnSalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        menuInicio.add(btnSalir);

        barraMenu.add(menuInicio);

        menuUsuarios.setText("Usuarios");

        btnCrearUsuario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));
        btnCrearUsuario.setText("Crear usuario");
        btnCrearUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearUsuarioActionPerformed(evt);
            }
        });
        menuUsuarios.add(btnCrearUsuario);

        btnModificarUsuario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_MASK));
        btnModificarUsuario.setText("Modificar usuario");
        btnModificarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarUsuarioActionPerformed(evt);
            }
        });
        menuUsuarios.add(btnModificarUsuario);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("Eliminar Usuario");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        menuUsuarios.add(jMenuItem2);

        btnVerUsuario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        btnVerUsuario.setText("Ver Usuario");
        btnVerUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerUsuarioActionPerformed(evt);
            }
        });
        menuUsuarios.add(btnVerUsuario);

        barraMenu.add(menuUsuarios);

        setJMenuBar(barraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblBienvenido1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lblBienvenido, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnVentas)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnBusqueda))))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lblBienvenido)
                .addGap(18, 18, 18)
                .addComponent(lblBienvenido1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBusqueda)
                    .addComponent(btnVentas))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // Salir de todo el sistema
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnModificarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarUsuarioActionPerformed
        // TODO add your handling code here:
        FrmModificarUsuario frmModificarUsuario = new FrmModificarUsuario();
        frmModificarUsuario.setVisible(true);
    }//GEN-LAST:event_btnModificarUsuarioActionPerformed

    private void btnVerUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerUsuarioActionPerformed
        // TODO add your handling code here:
        JTable tablaResultado = crearTabla();
        JScrollPane sp = new JScrollPane(tablaResultado);
        
        JFrame frmVerUsuarios = new JFrame();
        
        frmVerUsuarios.setTitle("Ver usuairos");
        frmVerUsuarios.setLocationRelativeTo(null);
        frmVerUsuarios.add(sp);
        frmVerUsuarios.setSize(800,300);
        frmVerUsuarios.setVisible(true);
        
    }//GEN-LAST:event_btnVerUsuarioActionPerformed

    private void btnCrearUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearUsuarioActionPerformed
        // TODO add your handling code here:
        FrmCrearUsuario crearUsuario = new FrmCrearUsuario();
        crearUsuario.setVisible(true);
        
    }//GEN-LAST:event_btnCrearUsuarioActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        FrmEliminarUsuario frmEliminarUsuario = new FrmEliminarUsuario();
        frmEliminarUsuario.setVisible(true);
        
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void btnVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVentasActionPerformed
        // TODO add your handling code here:
        FrmMenuVentas frmMenuVentas= new FrmMenuVentas();
        frmMenuVentas.setVisible(true);
        
    }//GEN-LAST:event_btnVentasActionPerformed

    private void btnBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBusquedaActionPerformed
        // TODO add your handling code here:
        FrmMenuBusqueda frmBusqueda= new FrmMenuBusqueda();
        frmBusqueda.setVisible(true);
    }//GEN-LAST:event_btnBusquedaActionPerformed
    
    /*
        Metodo que permite crear la estructura de la tabla.
        Las columnas son Nombre y descripcion
        Las filas se hacen por medio de un ciclo para obtener el dato de cada objeto rol guardado
        El metodo devuelve una tabla
     */
    private JTable crearTabla() {
        
        String columna[] = {"Nombre", "Contraseña","Correo Electronico","Roles"};
        
        DefaultTableModel tablaModelo = new DefaultTableModel(columna, 0);
        
        for (int i = 0; i < frmLogin.mListaDeUsuarios.size(); i++) {
            
            String nombre = frmLogin.mListaDeUsuarios.get(i).getNombre();
            String pass = frmLogin.mListaDeUsuarios.get(i).getPass();
            pass= "****";
            String correoElectronico = frmLogin.mListaDeUsuarios.get(i).getCorreoElectronico();
            
            //Mostrare los roles como una lista separada por comas
            
            Object[] listaRoles= frmLogin.mListaDeUsuarios.get(i).getListaRoles().toArray();
            Object[] fila = {nombre, pass, correoElectronico, Arrays.toString(listaRoles)};
            
            tablaModelo.addRow(fila);
        }
        
        JTable tablaRoles = new JTable(tablaModelo);
        tablaRoles.setBounds(50, 50, 200, 300);
 
        return tablaRoles;
        
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barraMenu;
    private javax.swing.JButton btnBusqueda;
    private javax.swing.JMenuItem btnCrearUsuario;
    private javax.swing.JMenuItem btnModificarUsuario;
    private javax.swing.JMenuItem btnSalir;
    private javax.swing.JButton btnVentas;
    private javax.swing.JMenuItem btnVerUsuario;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JLabel lblBienvenido;
    private javax.swing.JLabel lblBienvenido1;
    private javax.swing.JMenu menuInicio;
    private javax.swing.JMenu menuUsuarios;
    private javax.swing.JPanel pnlBlanco;
    private javax.swing.JPanel pnlFondo;
    // End of variables declaration//GEN-END:variables

}
